# Compare the different implementations of the same model

Import libraries

In [20]:
%load_ext autoreload
%autoreload 2

import sys
import warnings
sys.path.append('..')
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import pingouin as pg
import plotly.express as px
import torch

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Import local moduls (rerun this if you change something in the local modules)

In [21]:
import run_original
import utils

In [22]:
revaluation_scores = run_original.run_original()

[[ 9.71 10.62  8.54]
 [11.74  9.55  8.57]
 [11.87 10.91  8.82]
 [11.44 11.16  8.73]
 [10.54  8.72  8.71]
 [10.72  8.01  8.64]
 [ 8.8   8.4   9.  ]
 [10.73  9.31  8.23]
 [11.12 11.43  8.61]
 [10.26  9.09  8.91]
 [10.53 10.27  8.63]
 [ 9.14  7.75  8.82]
 [ 7.97  8.36  8.52]
 [ 9.87  6.36  8.62]
 [10.45  8.93  8.74]
 [12.32 11.16  8.9 ]
 [ 9.4   8.29  8.84]
 [ 7.48  5.7   8.64]
 [ 9.88  8.96  8.53]
 [11.47 11.17  8.57]
 [ 9.41  8.44  8.78]
 [ 9.44  9.32  8.72]
 [11.52  9.44  8.53]
 [10.64 10.05  9.02]
 [ 9.19  7.99  8.82]
 [ 8.99  9.17  8.71]
 [10.07  9.82  8.71]
 [11.88 10.56  8.33]
 [10.23  8.04  8.53]
 [10.53  7.9   8.26]
 [10.01  7.9   8.52]
 [10.15  9.39  8.63]
 [ 9.02  7.83  8.84]
 [11.22  8.8   8.51]
 [ 7.9   8.55  8.64]
 [ 8.61  7.44  8.51]
 [11.95 10.62  8.8 ]
 [11.97 11.32  8.92]
 [10.06  8.09  8.73]
 [12.1  10.59  8.41]
 [ 9.81  8.33  8.53]
 [ 9.06  7.9   8.63]
 [11.31 11.24  8.61]
 [ 7.    6.09  8.54]
 [ 9.43  7.98  8.82]
 [ 9.94  8.44  8.82]
 [10.67  8.77  8.71]
 [ 8.48  6.69

In [24]:
# Model data
plot_data = pd.DataFrame(revaluation_scores[:,:2],columns=['Reward<br>Revaluation','Transition<br>Revaluation']).melt(var_name='Condition',value_name='Revaluation Score')
scaling_factor = .5199/revaluation_scores[:,0].mean() # Scale revaluation scores to match mean of behavioral data
t_test_results = pg.pairwise_tests(plot_data,between='Condition',dv='Revaluation Score')

plot_data['Revaluation Score'] *= scaling_factor
plot_data = plot_data.groupby(['Condition']).agg(**{'Revaluation Score': ('Revaluation Score','mean'), 'error': ('Revaluation Score','sem')}).reset_index()
fig = px.bar(plot_data,range_y=[0,1],x='Condition',y='Revaluation Score',color='Condition',error_y='error',
             color_discrete_sequence=['#0099C6','#FF9900'],title='Model Performance')
fig.update_layout(showlegend=False)
fig.show()